-- Version: 1.0.1
-- Description: Future migrations placeholder
-- Backend file: future_migrations
-- 
-- ATTENTION: This file is intended for future database schema migrations.
-- 
-- When developing new functionality that requires database schema changes:
-- 1. Create a new migration file with a number greater than the current one
-- 2. Add a description of the changes in the comments
-- 3. Ensure the migration can be applied to an existing database
-- 4. Test the migration on a copy of the data
-- 
-- Migration structure example:
-- -- Version: 1.7.3
-- -- Description: Add new table for feature X
-- -- Backend file: add_feature_x_table
-- 
-- CREATE TABLE IF NOT EXISTS app.new_table (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     name VARCHAR(100) NOT NULL,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
-- 
-- -- Add a record of the applied migration
-- INSERT INTO app.schema_migrations (version, description, checksum) 
-- VALUES ('002', 'Add new table for feature X', 'checksum_here');
